### ISSUE TITLE
Make this work including subdirectories

### ISSUE THREAD

**Issue by amolgawai** [Acidham/alfred-markdown-notes#1]
First of all, thanks a lot for making this workflow. I purchased the power pack just for this workflow.
I use markdown a lot and all my markdown files are structured into subdirectories of my main directory. It seems that this workflow only works on the current path set and does not work recursively into subdirectories. Would it be possible to add this feature?

**Comment by Acidham** [comment]
Unfortunately not because this would lead into performance loss when diving into sub directories. 
I wrote this WF to solve exactly this use case to keep it flat and leverage the search.

**Comment by amolgawai** [comment]
That's a huge bummer... :-(

**Comment by ibarnick** [comment]
Agree that this is a bummer. Was about to make this exact same feature request before seeing that the issue was already opened/closed.

**Comment by slavakurilyak** [comment]
+1 for supporting multiple directories

**Comment by vkdubov** [comment]
+1 for supporting multiple directories

**Comment by macx** [comment]
@Acidham Please re-open this ticket and rethink your decision!

**Comment by Acidham** [comment]
Decided ;)
