### ISSUE TITLE
Encoding issue with the argument?

### ISSUE THREAD

**Issue by bcdavasconcelos** [Acidham/alfred-markdown-notes#10]
Hi, thanks for this workflow.

Is there any known issue related to diacritics?
Over here search doesn't work if the argument contains any diacritics (`á, é, í, ç, à, è, ã, ᾶ, ἅ, etc`. I checked the debugger and noticed the argument is getting encoded into code points (e.g. `Glossário` → `Glossa\u0301rio\`). I looked through the code and found the `UMLAUT_REPL_MAP`, but that appears to be commented out. 

It is worth mentioning that this happens only while perfoming a searching. If I just request the tags, it will find and display tags containing diacritics without problems.

Any ideas?

Using version MD Notes 3.0.4 and Python 3.8.2

**Comment by Acidham** [comment]
Please test by downloading https://github.com/Acidham/alfred-markdown-notes/blob/master/Markdown%20Notes.alfredworkflow

**Comment by bcdavasconcelos** [comment]
Thank you for the swift reply. Works perfectly!
