### ISSUE TITLE
"No such file or directory" Error on all workflow commands

### ISSUE THREAD

**Issue by montemartin** [Acidham/alfred-markdown-notes#11]
I can't get the workflow functioning. Every command (including `.mdconfig`) throws the follow error pattern in the Alfred Debugger. 

```
[18:33:45.281] Markdown Notes[Script Filter] Queuing argument ''
[18:33:45.351] Markdown Notes[Script Filter] Script with argv '' finished
[18:33:45.356] ERROR: Markdown Notes[Script Filter] Code 127: env: python3: No such file or directory
```

`Python3` works on the command line and is in my $PATH so I'm stuck on what the error is. I can't figure out how to get a more verbose error message so I'm hoping you can help.

**Comment by Acidham** [comment]
Is Python3 installed on your computer? 

What is the output of  `python3 -V`?
What is the output of `type -a python3`?

BTW: You can set up the WF also in Alfred Preferences by clicking on the `[x]` top right corner. But I assume you will get the same error when running `mds` for example.

**Comment by montemartin** [comment]
Yes Python3 is installed and functioning. 
```
$python3 -V
Python 3.8.5

$type -a python3
python3 is /usr/local/bin/python3
python3 is /usr/local/bin/python3
python3 is /usr/local/bin/python3
```

**Comment by Acidham** [comment]
That's weird. It seems python3 is messed up on your computer. 

What happens when you exec `where env`? 
And `/usr/bin/env python3 --version` ?

**Comment by montemartin** [comment]
```
$where env
/usr/bin/env

$/usr/bin/env python3 --version
Python 3.8.5
```

Python is installed via brew, but that shouldn't make a difference. I've also already tried removing it and reinstalling.

**Comment by montemartin** [comment]
It is installed via brew, but that shouldn't make a difference. I've also already tried removing it and reinstalling.

**Comment by Acidham** [comment]
I only know that Alfred is not loading your env (bash_config or zshrc) and therefore env python3 seems not to work in your environment.

For time being and get WF to work you can change the shebang first line (#!/usr/bin...) in python files to your python path `#!/usr/local/bin/python3`

Next, search google...there are various things that you can try. For me it's hard to Analyse your env.
