### ISSUE TITLE
I don't really understand how the bookmarks work

### ISSUE THREAD

**Issue by nwhistler** [Acidham/alfred-markdown-notes#12]
I can setup the bookmark tag in the variable but everytime I search for a bookmark it can't find a URL. What is the format needed?

**Comment by Acidham** [comment]
Just the name without anything should work, e.g. URL or BOOKMARK

Then type `mdb` followed by the any search term and should find notes with tag URL resp. BOOKMARK and with bookmarked url in the form of `[mypage](http://mypage.com)`
