### ISSUE TITLE
Getting started issues

### ISSUE THREAD

**Issue by svinter** [Acidham/alfred-markdown-notes#13]
Could you point to a sample template and md file to get started? Out of the box and stuck on the template files. 

Alfred, Python, and Typora are all installed and appear to be working fine. The mdc workflow successfully creates an md file but nothing else is working. Thanks!

Steve

**Comment by Acidham** [comment]
You said mdc creates a file successfully? Is the file available in target path?

When you search with a search term...will the file be found ?

Any debugging output when exec mds?

**Comment by svinter** [comment]
Yes, mdc creates the file successfully in the target path.  There are 5 other .md files in that directory, but none seem accessible/searchable. 

Typing md creates a drop menu of Markdown Note options as expected (Create note based on Template, Search in MD Notes, etc.)

Typing mds raises a prompt for a specific .pdf file in another directory unrelated to this

Typing mds <term> prompts for a search in Google, Wikipedia, and Amazon (same as typing random text into Alfred).

FWIW, I haven't set Template.md because I don't know what to set it to.

**Comment by Acidham** [comment]
Template.md is just the default template but you can ignore it for time being.

Let's focus on mds to search an note. Can you open WF debugger, top right bug-icon, an exec a search. I expect there must be an error thrown.
BTW: your behavior seems to mismatch with Alfred standard search. Can you change that in Ed scriptfilter e.g. $mds 

What did you add as notes path? Just the format/pattern?

**Comment by svinter** [comment]
You're right. WF debugger after typing mds:

[15:46:49.400] Markdown Notes[Script Filter] Queuing argument ''
[15:46:49.425] Markdown Notes[Script Filter] Script with argv '' finished
[15:46:49.427] ERROR: Markdown Notes[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Settings are here: https://share.getcloudapp.com/OAuqbBWn

Sorry, I'm not sure what "Ed scriptfilter" refers to, but here is what I see for mds: https://share.getcloudapp.com/OAuqbB8J

**Comment by Acidham** [comment]
The error looks strange. You maybe setup python in the wrong way. Please take a look here and follow instructions: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Re scriptfilter, your screenshot, just change Keyword: mds to something like $mds 
Then you need to type $mds instead of mds for searching. You can change it back to mds once wf is working.

**Comment by svinter** [comment]
I installed xcode and ran into the xcrum problem, which was fixed by "xcode-select --install", and voila -- runs beautifully!   Thanks!

Now running mds, I get the correct list of files *.md files. I then type "mds journey" and it selects the correct file with "journey" in it. When I hit return, it opens the correct file, but does not position the current to the occurrence of "journey". The log looks like what I'd expect:

"cmd": {
                    "arg": "/Users/stevevinter/Documents/Markdown/mybooks.md>journey",
                    "subtitle": "Enter Actions Menu for the Note...",


Is it supposed to position me to the position in the file where the string is found? 

And then there's the template ignorance I have, as well.

**Comment by Acidham** [comment]
Great we sorted that out!

Re jump to the occurrence in the file...this is not expected. The wf just show you the file where the term was found an open it in typora.

Re template, this works like 
- you create a md file with title `mdc Template`
- add content as you wish and use placeholders described in docs
- in wf Setup `Template.md` points to this file as default. This can be changed to any file name.

Furthermore you can add as many templates to the system. The only thing that must match is template tag. This means all md notes with that tag are used as templates and listed when exec `mdc`

**Comment by svinter** [comment]
Yes, thanks *so* much for your help.

Yes, I understand the mechanics of how Templates work. I was more asking to see examples of working ones as my first attempt to set it up didn't work for syntactic reasons.

As to the use of the search results: my original intent was to use templates to define a set of "records", to search for a specific record (or set of records), and then extract the full record and pass it on to another workflow. This would be a more generalized approach to the Full Text Search (https://www.alfredforum.com/topic/12131-full-text-search-anything/) workflow. Would this be a simple extension to what you already have, or not so much?   

Regardless, again: thank you so much!

**Comment by Acidham** [comment]
Glad that we were able to get it work!

Not sure on what the exact use case is but I suggest creating a new issue and describe in detail what you would like to achieve. We can then take it from there if it feasible or not.

Closing this issue for now....
