### ISSUE TITLE
High Sierra and python3

### ISSUE THREAD

**Issue by pdazero** [Acidham/alfred-markdown-notes#14]
Hi @Acidham , Im using an old mac with High Sierra, and there is no way to put python3 on /usr/bin unless SIP is disabled, which is not recommended.

I had to change all .py script's hashbang to /usr/local/bin/python3 instead.

I could suggest using the ENV path, or maybe PYENV such as ~/.pyenv/shims/python, or just use /usr/local/bin/python3 which would work in all MacOS versions I think.

Best,

**Comment by Acidham** [comment]
This problem is part of a longer discussion but finally was fixed. I will rollout improvement release in a minute... Please check.
