### ISSUE TITLE
Workflow looks stuck trying to initialize the Python3 alias

### ISSUE THREAD

**Issue by 1activegeek** [Acidham/alfred-markdown-notes#20]
In taking a look at a few of the bits you have in the script, it appears something is broken in trying to initialize the python3 alias you are using. Attempts at running the py3.sh script by itself just to see output, is resulting in the following errors and output:

```
user@host user.workflow.8C733D3E-56ED-4C07-AFF7-F57B1EFFDB3C % /Users/user/Documents/appdata/Alfred.alfredpreferences/workflows/user.workflow.8C733D3E-56ED-4C07-AFF7-F57B1EFFDB3C/py3.sh 
mkdir: .: No such file or directory
/Users/user/Documents/appdata/Alfred.alfredpreferences/workflows/user.workflow.8C733D3E-56ED-4C07-AFF7-F57B1EFFDB3C/py3.sh: line 58: /py3: Read-only file system
{
    "items": [
        {
            "title": "Config: Python3 was found at /usr/bin/python3.",
            "subtitle": "Version: 3.89, Proceed typing query or re-run worfklow",
        }
    ]
}
/Users/user/Documents/appdata/Alfred.alfredpreferences/workflows/user.workflow.8C733D3E-56ED-4C07-AFF7-F57B1EFFDB3C/py3.sh: line 120: /py3: No such file or directory
```

Additionally, I see there is an alias that should be created in the WF directory called `py3` - but I don't see this file being created whether I run this py3.sh manually or as part of the workflow. The end result of anything I try in the workflow just outputs the following:

```
{
    "items": [
        {
            "title": "Config: Python3 was found at /usr/bin/python3.",
            "subtitle": "Version: 3.89, Proceed typing query or re-run worfklow",
        }
    ]
}
```

OS: macOS Monterey 12.3.1
Python: Python3 3.89 (as seen 😄)
Goal: Using your bits on grabbing file URL in markdown format - after that I may expand usage for some other bits, but the core I'm looking for is your file URL grabber.

**Comment by Acidham** [comment]
Re. First error: Did you execute outside of Alfred?

What is the content of the folder `/Users/user/Library/Application Support/Alfred/Workflow Data/com.apple.alfred.workflow.mdnotes` after you executed the workflow?

**Comment by 1activegeek** [comment]
> Re. First error: Did you execute outside of Alfred?

Yes that was done outside of Alfred, so I suspected that some of that was likely due to not being run by the Alfred binary vs me manually running it from the terminal. I just did that to see if anything glaring popped out.

> What is the content of the folder `/Users/user/Library/Application Support/Alfred/Workflow Data/com.apple.alfred.workflow.mdnotes` after you executed the workflow?

That folder does appear to exist, and has just the `py3` file. Inside, it has a single line pointing to the python3 binary:
`export py3='/usr/bin/python3'`

**Comment by Acidham** [comment]
That's it, the script is not doing additional magic

**Comment by 1activegeek** [comment]
Ok, took that info and tried out the Debug on Alfred side - didn't realize I could get info without all the Debug objects. Interestingly it seems there was an issue with the location of notes. Sorry for the goose chase. I pasted it in an escaped format, when it didn't need it that way. All good now. 

Now I just need to figure out adapting your current script for the link formats as I want to leave the files in their original locations. But you've provided a perfect jumping off point. Thanks for the nice workflow!
