### ISSUE TITLE
[FR] Allow creating note with tags

### ISSUE THREAD

**Issue by tiptronic** [Acidham/alfred-markdown-notes#4]
If I search for a note (e.g. `mds Hello`) which does not exist, or just create a new note, it would be great, if I could create a note with TAGS already, e.g. using this syntax:

mdc `Hello #world,#folks`  (or `Hello #world,folks`), where 'world' and 'folks' are tags.

**Comment by Acidham** [comment]
Done with Release v1.9

**Comment by tiptronic** [comment]
Cool! 👍 
But here's a catch:
If I enter `mdc hello world test`
- the file now has a name `hello world test python.md`, which doesn't feel right and tends to give troubles, if you plan to sync those files to e.g. a website (it shouldn't contain spaces at least, but ideally it would only contain the title - in this case `hello.md`)

If I enter `mdc hello #world test`: for some reason the file is named `hello test 22.12.2019.md`for me..

- tags are now written as `Tags: #hello world test python`. I'd rather separate tags using a comma-delimiter, or - even better - make it `Frontmatter` compatible: `tags: ["world", "test", "python"]` (this is used by most sites or note-taking apps **I** know of.

Otherwise this is a pretty cool enhancement!

**Comment by tiptronic** [comment]
Ah - at least I found out, why the file-name got a date: my `Template.md` was:

> {title}
> {date}

Not sure, if I like to create a filename based on my template-variables. I think it's cleaner to keep simple filenames.

**Comment by Acidham** [comment]
> If I enter mdc hello #world test: for some reason the file is named hello test 22.12.2019.md for me..

The result with `mds` does not show you the filename its the first Headline in the md document. Filename will only be shown as title as fallback in case the headline was entered. In your case, as you figured out yourself, you put the placeholders in the template.

> make it Frontmatter compatible: tags: ["world", "test", "python"] (this is used by most sites or note-taking apps I know of.

Yeah this was my initial idea but there is a valid use case why I am using '#':  I am using 1Writer on my iPhone and I am basically syncing all my md notes with 1Writer on my iPhone. 1Writer recognize #tag as tag and show it in a list similar to bear. I think iAWriter is doing the same. When I would make in Frontmatter compatible 1Writer or iAWriter both would not recognize those tags.

**Comment by tiptronic** [comment]
> The result with `mds` does not show you the filename its the first Headline in the md document. Filename will only be shown as title as fallback in case the headline was entered. In your case, as you figured out yourself, you put the placeholders in the template.

Jep, but I was talking about the 'real' filename (as shown in Finder).

> Yeah this was my initial idea but there is a valid use case why I am using '#': I am using 1Writer on my iPhone and I am basically syncing all my md notes with 1Writer on my iPhone. 1Writer recognize #tag as tag and show it in a list similar to bear. I think iAWriter is doing the same. When I would make in Frontmatter compatible 1Writer or iAWriter both would not recognize those tags.

Understood! 👍 

Maybe we can use a setting/preference to allow formatting tags as Frontmatter (or strings)?
