### ISSUE TITLE
Change note title

### ISSUE THREAD

**Issue by simeond** [Acidham/alfred-markdown-notes#5]
Hello.  This is a really great workflow!

I am trying to figure out a way of creating notes that save with the title "{date}_{title}.md"
I couldn't see where I can change that

**Comment by Acidham** [comment]
The placeholders are currently only supported in the MD Note. The Title will be replaced on when note is created but this does not influence the file name with date placeholder.

**Comment by simeond** [comment]
Ok, I think I misunderstood. I thought the title formed the file name.  I guess my question is more - how do I get the file name to be "{date}_{title}.md"?

**Comment by Acidham** [comment]
Just Type 'mdc 03.09.2020 MyTtile' this creates a document with the filename 03.09.2020 MyTtile.md with Title (heading 1) "03.09.2020 MyTtile"
