### ISSUE TITLE
Creating notes error

### ISSUE THREAD

**Issue by yihou** [Acidham/alfred-markdown-notes#6]
I have configured `default_template`, `path_to_notes`
```
default_template: ~/md_notes/Template.md
path_to_notes: ~/md_notes
```

Here is the error I got:
```
"path/to/workflow/create_note.py", line 21, in <module>
    fPath = Note.create_note()
  File "path/to/workflow/MyNotes.py", line 669, in create_note
    sys.stderr.write(e)
TypeError: expected a string or other character buffer object
```

**Comment by Acidham** [comment]
Ok please correct setting as follows:
* `default_template`: `Template.md` (without path just filename)
* `path_to_notes` : use full path eg `/Users/yihou/md_notes`

**Comment by yihou** [comment]
ahh that works, love it ❤️ thank you so much!
