### ISSUE TITLE
Quicklook with <shift> from alfred not working

### ISSUE THREAD

**Issue by nathankoerschner** [Acidham/alfred-markdown-notes#9]
Hey there, 

After installing the workflow, then installing QLMarkdown, I am not able to see the quickviews of documents from alfred. Both are working great separately. 

Maybe I these need to be installed in a certain order? Which part of the workflow has the bit that invokes the QL of the selected document?

**Comment by Acidham** [comment]
You may need to restart your computer. The workflow does not use any special implementation it is QL from Alfred OOTB.

**Comment by nathankoerschner** [comment]
Figured it out-- its a tap on shift, instead of a hold. I wonder if this can be changed in Alfred...
